# NOTE: Local environment will not work with current setup: 
#       *db is not set up with postgresql, and sqlite3 will not work because of difference in how sqlite3 and postgresql handle json fields

# database.yml
# database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: gumroad-demo_production
  url: <%= ENV['DATABASE_URL'] %>